version = 1

exclude_patterns = [
  "examples/**"
]

test_patterns = [
  "test/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/rockset/rockset-go-client"
